export const SHIPPING_MANIFEST_SCHEMA = "sovereign-standard-shipping-manifest/v1";

export interface PostalAddress {
  line1: string;
  line2: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
}

export interface ShippingParty {
  name: string;
  address: PostalAddress;
}

export interface ShippingRecord {
  shipment_id: string;
  order_id: string;
  fulfilled_at: string;
  vessel: number;
  recipient: ShippingParty;
}

export interface ShippingManifest {
  schema: typeof SHIPPING_MANIFEST_SCHEMA;
  manifest_date: string;
  label_size_inches: { width: 3; height: 2 };
  origin: ShippingParty;
  shipments: ShippingRecord[];
}

function object(value: unknown, field: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${field} must be an object`);
  return value as Record<string, unknown>;
}

function text(value: unknown, field: string, optional = false): string {
  const normalized = String(value ?? "").trim().replace(/\s+/g, " ");
  if (!normalized && !optional) throw new Error(`${field} is required`);
  return normalized;
}

function address(value: unknown, field: string): PostalAddress {
  const source = object(value, field);
  return {
    line1: text(source.line1, `${field}.line1`),
    line2: text(source.line2, `${field}.line2`, true),
    city: text(source.city, `${field}.city`),
    state: text(source.state, `${field}.state`),
    postal_code: text(source.postal_code, `${field}.postal_code`),
    country: text(source.country || "US", `${field}.country`).toUpperCase(),
  };
}

function party(value: unknown, field: string): ShippingParty {
  const source = object(value, field);
  return { name: text(source.name, `${field}.name`), address: address(source.address, `${field}.address`) };
}

export function parseShippingManifest(sourceText: string): ShippingManifest {
  let parsed: unknown;
  try {
    parsed = JSON.parse(sourceText);
  } catch {
    throw new Error("Dispatch requires the private JSON manifest generated by Sovereign Standard");
  }
  const source = object(parsed, "manifest");
  if (source.schema !== SHIPPING_MANIFEST_SCHEMA) throw new Error(`Unsupported manifest schema: ${String(source.schema || "missing")}`);
  const manifestDate = text(source.manifest_date, "manifest_date");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(manifestDate)) throw new Error("manifest_date must use YYYY-MM-DD");
  const labelSize = object(source.label_size_inches, "label_size_inches");
  if (Number(labelSize.width) !== 3 || Number(labelSize.height) !== 2) throw new Error("Dispatch currently requires the canonical 3 x 2 inch label profile");
  if (!Array.isArray(source.shipments) || !source.shipments.length) throw new Error("Manifest contains no fulfilled shipments");

  const seen = new Set<string>();
  const shipments = source.shipments.map((value, index): ShippingRecord => {
    const shipment = object(value, `shipments[${index}]`);
    const shipmentID = text(shipment.shipment_id, `shipments[${index}].shipment_id`);
    if (seen.has(shipmentID)) throw new Error(`Duplicate shipment id: ${shipmentID}`);
    seen.add(shipmentID);
    const vessel = Number(shipment.vessel);
    if (!Number.isInteger(vessel) || vessel < 0) throw new Error(`shipments[${index}].vessel must be a non-negative integer`);
    return {
      shipment_id: shipmentID,
      order_id: text(shipment.order_id, `shipments[${index}].order_id`),
      fulfilled_at: text(shipment.fulfilled_at, `shipments[${index}].fulfilled_at`),
      vessel,
      recipient: party(shipment.recipient, `shipments[${index}].recipient`),
    };
  });

  return {
    schema: SHIPPING_MANIFEST_SCHEMA,
    manifest_date: manifestDate,
    label_size_inches: { width: 3, height: 2 },
    origin: party(source.origin, "origin"),
    shipments,
  };
}

export function addressLines(value: PostalAddress): string[] {
  const lines = [value.line1];
  if (value.line2) lines.push(value.line2);
  lines.push(`${value.city}, ${value.state} ${value.postal_code}`);
  if (!["US", "USA", "UNITED STATES"].includes(value.country.toUpperCase())) lines.push(value.country);
  return lines;
}

export function fittedFontSize(value: string, maximum: number, threshold: number, minimum: number): number {
  if (value.length <= threshold) return maximum;
  return Math.max(minimum, maximum * threshold / value.length);
}
